import { defaultPaginationKeywords, defineConfig } from "@hey-api/openapi-ts"
import "dotenv/config"

// "openapi": "node -r dotenv/config ./node_modules/.bin/openapi-ts"

// const username = process.env.OPENAPI_USERNAME
// const password = process.env.OPENAPI_PASSWORD
const apiBaseUrl = process.env.OPENAPI_BASE_URL

if (!apiBaseUrl) {
	throw new Error("OPENAPI_BASE_URL is not defined in environment variables.")
}
// if ((username && !password) || (!username && password)) {
// 	throw new Error("Both OPENAPI_USERNAME and OPENAPI_PASSWORD must be set together.")
// }

// const auth = Buffer.from(`${username}:${password}`).toString("base64")

export default defineConfig([{
	input: {
		// path: "../backend/openapi.json",
		path: apiBaseUrl,
		// fetch: {
		// 	headers: {
		// 		Authorization: `Basic ${auth}`,
		// 	},
		// },
	},
	output: {
		path: "shared/openapi",
		postProcess: ["eslint"],
		header: [
			"// <AUTO_GENERATED> DO NOT EDIT THIS FILE DIRECTLY.",
			"// This file is auto-generated by @hey-api/openapi-ts",
		],
	},
	parser: {
		pagination: {
			keywords: [
				...defaultPaginationKeywords,
				"after_id",
				"after_created_at",
				"limit",
			],
		},
		filters: {
			tags: {
				include: ["ARCustomers", "ICItems", "ICCategories", "ICItemPricing", " OEOrders", "OEInvoices"],
			},
		},
	},
	plugins: [
		{
			name: "@hey-api/sdk",
			auth: true,
			client: "@hey-api/client-ofetch",
			transformer: "@hey-api/transformers",
			validator: {
				request: "zod",
			},
		},
		{
			name: "@hey-api/typescript",
			enums: "javascript",
		},
		{
			name: "@hey-api/transformers",
			dates: true,
			// just using zod's int64 support.
			// json cannot transport bigints as json number is 2^53. bigint is 2^63-1
			// bigint: true,
		},
		{
			name: "@hey-api/client-ofetch",
			throwOnError: true,
		},
		{
			"name": "zod",
			"compatibilityVersion": "mini",
			"exportFromIndex": true,
			"~resolvers": {
				string(ctx) {
					const { $, schema, symbols } = ctx
					const { z } = symbols
					if (schema.format === "int64") {
						return $(z)
							.attr("string")
							.call()
							.attr("refine")
							.call(
								$.func()
									.param("val")
									.do(
										$.try(
											$(z)
												.attr("int64")
												.call()
												.attr("parse")
												.call($("BigInt").call("val")),
											$.return($.literal(true)),
										).catch($.return($.literal(false))),
									),
								$.object().prop("message", $.literal("Must be a valid int64 string")),
							)
					}
				},
				// integer(ctx) {
				// 	const { $, symbols } = ctx
				// 	const { z } = symbols
				// 	if (ctx.schema.format === "int64") {
				// 		return $(z).attr("string").call().attr("refine").call(
				// 			$.func().param("val").do(
				// 				$.try(
				// 					$(z).attr("int64").call().attr("parse").call($("BigInt").call("val")),
				// 					$.return($.literal(true)),
				// 				).catch($.return($.literal(false))),
				// 			),
				// 			$.object().prop("message", $.literal("Must be a valid int64 string")),
				// 		)
				// 	}
				// },
			},
		},
	],
}])
