import { defaultPaginationKeywords, defineConfig } from "@hey-api/openapi-ts"
import "dotenv/config"

// "openapi": "node -r dotenv/config ./node_modules/.bin/openapi-ts"

// const username = process.env.OPENAPI_USERNAME
// const password = process.env.OPENAPI_PASSWORD
const apiBaseUrl = process.env.OPENAPI_BASE_URL

if (!apiBaseUrl) {
	throw new Error("OPENAPI_BASE_URL is not defined in environment variables.")
}
// if ((username && !password) || (!username && password)) {
// 	throw new Error("Both OPENAPI_USERNAME and OPENAPI_PASSWORD must be set together.")
// }

// const auth = Buffer.from(`${username}:${password}`).toString("base64")

// Path params shared by every Sage 300 OData route. They live in the
// `/v{apiVersion}/{tenant}/{company}` prefix and add no meaning to the
// generated symbol names, so we drop them when building operation ids.
const SHARED_PATH_PARAMS = new Set(["apiVersion", "tenant", "company"])

/**
 * Builds a concise `operationId` from an OData route. The Sage 300 spec ships
 * no operation ids, so @hey-api derives names from `METHOD + path` — which bakes
 * the shared `/v{apiVersion}/{tenant}/{company}` prefix into every SDK function,
 * type, and zod schema (e.g. `arCustomersGetByApiversionAndTenantAndCompany`).
 *
 * Setting the id here (before parsing) shortens the name everywhere downstream:
 *   GET  /v{apiVersion}/{tenant}/{company}/AR/ARCustomers
 *     -> ARCustomersGet                      -> arCustomersGet / ArCustomersGetData
 *   GET  /v{apiVersion}/{tenant}/{company}/AR/ARCustomers('{CustomerNumber}')
 *     -> ARCustomersGetByCustomerNumber      -> arCustomersGetByCustomerNumber
 */
function buildOperationId(method: string, path: string, tag: string | undefined): string {
	// OData key params, e.g. {CustomerNumber}, minus the shared prefix params.
	const keys = Array.from(path.matchAll(/\{([^}]+)\}/g), match => match[1])
		.filter((key): key is string => Boolean(key) && !SHARED_PATH_PARAMS.has(key))

	// Last route segment with any OData key suffix `(...)` stripped off, e.g.
	// `ARCustomers` from `/AR/ARCustomers('{CustomerNumber}')`.
	const lastSegment = path
		.split("/")
		.filter(Boolean)
		.pop()
		?.replace(/\(.*\)$/, "")

	// Prefer the entity set tag (`ARCustomers`); fall back to the route segment.
	const entity = tag?.trim() || lastSegment || "operation"

	const verb = method.charAt(0).toUpperCase() + method.slice(1).toLowerCase()
	const byKeys = keys.length
		? `By${keys.map(key => key.charAt(0).toUpperCase() + key.slice(1)).join("And")}`
		: ""

	return `${entity}${verb}${byKeys}`
}

export default defineConfig([{
	input: {
		// path: "../backend/openapi.json",
		path: apiBaseUrl,
		// fetch: {
		// 	headers: {
		// 		Authorization: `Basic ${auth}`,
		// 	},
		// },
	},
	output: {
		path: "shared/openapi",
		postProcess: ["eslint"],
		header: [
			"// <AUTO_GENERATED> DO NOT EDIT THIS FILE DIRECTLY.",
			"// This file is auto-generated by @hey-api/openapi-ts",
		],
	},
	parser: {
		patch: {
			// The Sage 300 spec has no operation ids, so override them with concise
			// names that omit the shared `/v{apiVersion}/{tenant}/{company}` prefix.
			operations: (method, path, operation) => {
				operation.operationId = buildOperationId(method, path, operation.tags?.[0])
			},
		},
		pagination: {
			keywords: [
				...defaultPaginationKeywords,
				"after_id",
				"after_created_at",
				"limit",
			],
		},
		filters: {
			tags: {
				include: ["ARCustomers", "ICItems", "ICCategories", "ICItemPricing", " OEOrders", "OEInvoices"],
			},
		},
	},
	plugins: [
		{
			name: "@hey-api/sdk",
			auth: true,
			client: "@hey-api/client-ofetch",
			transformer: "@hey-api/transformers",
			validator: {
				request: "zod",
			},
		},
		{
			name: "@hey-api/typescript",
			enums: "javascript",
		},
		{
			name: "@hey-api/transformers",
			dates: true,
			// just using zod's int64 support.
			// json cannot transport bigints as json number is 2^53. bigint is 2^63-1
			// bigint: true,
		},
		{
			name: "@hey-api/client-ofetch",
			throwOnError: true,
		},
		{
			"name": "zod",
			"compatibilityVersion": "mini",
			"exportFromIndex": true,
			"~resolvers": {
				string(ctx) {
					const { $, schema, symbols } = ctx
					const { z } = symbols
					if (schema.format === "int64") {
						return $(z)
							.attr("string")
							.call()
							.attr("refine")
							.call(
								$.func()
									.param("val")
									.do(
										$.try(
											$(z)
												.attr("int64")
												.call()
												.attr("parse")
												.call($("BigInt").call("val")),
											$.return($.literal(true)),
										).catch($.return($.literal(false))),
									),
								$.object().prop("message", $.literal("Must be a valid int64 string")),
							)
					}
				},
				// integer(ctx) {
				// 	const { $, symbols } = ctx
				// 	const { z } = symbols
				// 	if (ctx.schema.format === "int64") {
				// 		return $(z).attr("string").call().attr("refine").call(
				// 			$.func().param("val").do(
				// 				$.try(
				// 					$(z).attr("int64").call().attr("parse").call($("BigInt").call("val")),
				// 					$.return($.literal(true)),
				// 				).catch($.return($.literal(false))),
				// 			),
				// 			$.object().prop("message", $.literal("Must be a valid int64 string")),
				// 		)
				// 	}
				// },
			},
		},
	],
}])
