// <AUTO_GENERATED> DO NOT EDIT THIS FILE DIRECTLY.
// This file is auto-generated by @hey-api/openapi-ts

import type { ArCustomersGetByApiversionAndTenantAndCompanyResponse, ArCustomersGetByCustomernumberAndApiversionAndTenantAndCompanyResponse, IcCategoriesGetByApiversionAndTenantAndCompanyResponse, IcCategoriesGetByCategorycodeAndApiversionAndTenantAndCompanyResponse, IcItemPricingGetByApiversionAndTenantAndCompanyResponse, IcItemPricingGetByCurrencycodeAndUnformatteditemnumberAndPricelistcodeAndApiversionAndTenantAndCompanyResponse, IcItemsGetByApiversionAndTenantAndCompanyResponse, IcItemsGetByUnformatteditemnumberAndApiversionAndTenantAndCompanyResponse, OeInvoicesGetByApiversionAndTenantAndCompanyResponse, OeInvoicesGetByInvoiceuniquifierAndApiversionAndTenantAndCompanyResponse } from "./types.gen"

const sageCaSbsErpSage300ArWebApiModelsCustomerOptionalFieldValueSchemaResponseTransformer = (data: any) => {
	if (data.TypedValueFieldIndex) {
		data.TypedValueFieldIndex = BigInt(data.TypedValueFieldIndex.toString())
	}
	if (data.IntegerValue) {
		data.IntegerValue = BigInt(data.IntegerValue.toString())
	}
	if (data.DateValue) {
		data.DateValue = new Date(data.DateValue)
	}
	if (data.TimeValue) {
		data.TimeValue = new Date(data.TimeValue)
	}
	return data
}

const sageCaSbsErpSage300ArWebApiModelsCustomerSchemaResponseTransformer = (data: any) => {
	if (data.InactiveDate) {
		data.InactiveDate = new Date(data.InactiveDate)
	}
	if (data.DateLastMaintained) {
		data.DateLastMaintained = new Date(data.DateLastMaintained)
	}
	if (data.StartDate) {
		data.StartDate = new Date(data.StartDate)
	}
	if (data.CreditBureauDate) {
		data.CreditBureauDate = new Date(data.CreditBureauDate)
	}
	if (data.DateOfLastStatement) {
		data.DateOfLastStatement = new Date(data.DateOfLastStatement)
	}
	if (data.DateOfLastBalanceForwardStatement) {
		data.DateOfLastBalanceForwardStatement = new Date(data.DateOfLastBalanceForwardStatement)
	}
	if (data.DateOfLastRevaluation) {
		data.DateOfLastRevaluation = new Date(data.DateOfLastRevaluation)
	}
	if (data.DateOfLargestInvoice) {
		data.DateOfLargestInvoice = new Date(data.DateOfLargestInvoice)
	}
	if (data.DateOfHighestBalance) {
		data.DateOfHighestBalance = new Date(data.DateOfHighestBalance)
	}
	if (data.DateOfLargestInvoiceLastYear) {
		data.DateOfLargestInvoiceLastYear = new Date(data.DateOfLargestInvoiceLastYear)
	}
	if (data.DateOfHighestBalanceLastYear) {
		data.DateOfHighestBalanceLastYear = new Date(data.DateOfHighestBalanceLastYear)
	}
	if (data.DateOfLastActivity) {
		data.DateOfLastActivity = new Date(data.DateOfLastActivity)
	}
	if (data.DateOfLastInvoice) {
		data.DateOfLastInvoice = new Date(data.DateOfLastInvoice)
	}
	if (data.DateOfLastCreditNote) {
		data.DateOfLastCreditNote = new Date(data.DateOfLastCreditNote)
	}
	if (data.DateOfLastDebitNote) {
		data.DateOfLastDebitNote = new Date(data.DateOfLastDebitNote)
	}
	if (data.DateOfLastReceipt) {
		data.DateOfLastReceipt = new Date(data.DateOfLastReceipt)
	}
	if (data.DateOfLastDiscount) {
		data.DateOfLastDiscount = new Date(data.DateOfLastDiscount)
	}
	if (data.DateOfLastAdjustment) {
		data.DateOfLastAdjustment = new Date(data.DateOfLastAdjustment)
	}
	if (data.DateOfLastWriteOff) {
		data.DateOfLastWriteOff = new Date(data.DateOfLastWriteOff)
	}
	if (data.DateOfLastReturnedCheck) {
		data.DateOfLastReturnedCheck = new Date(data.DateOfLastReturnedCheck)
	}
	if (data.DateOfLastInterestCharge) {
		data.DateOfLastInterestCharge = new Date(data.DateOfLastInterestCharge)
	}
	if (data.NumberOfOptionalFields) {
		data.NumberOfOptionalFields = BigInt(data.NumberOfOptionalFields.toString())
	}
	if (data.DateOfLastRefund) {
		data.DateOfLastRefund = new Date(data.DateOfLastRefund)
	}
	if (data.NextClientUniqueID) {
		data.NextClientUniqueID = BigInt(data.NextClientUniqueID.toString())
	}
	if (data.CustomerOptionalFieldValues) {
		data.CustomerOptionalFieldValues = data.CustomerOptionalFieldValues.map((item: any) => sageCaSbsErpSage300ArWebApiModelsCustomerOptionalFieldValueSchemaResponseTransformer(item))
	}
	return data
}

const swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300ArWebApiModelsCustomerSchemaResponseTransformer = (data: any) => {
	if (data.value) {
		data.value = data.value.map((item: any) => sageCaSbsErpSage300ArWebApiModelsCustomerSchemaResponseTransformer(item))
	}
	return data
}

export const arCustomersGetByApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<ArCustomersGetByApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300ArWebApiModelsCustomerSchemaResponseTransformer(data)
	return data
}

export const arCustomersGetByCustomernumberAndApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<ArCustomersGetByCustomernumberAndApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300ArWebApiModelsCustomerSchemaResponseTransformer(data)
	return data
}

const sageCaSbsErpSage300IcWebApiModelsCategorySchemaResponseTransformer = (data: any) => {
	if (data.DateLastMaintained) {
		data.DateLastMaintained = new Date(data.DateLastMaintained)
	}
	if (data.DateInactive) {
		data.DateInactive = new Date(data.DateInactive)
	}
	return data
}

const swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsCategorySchemaResponseTransformer = (data: any) => {
	if (data.value) {
		data.value = data.value.map((item: any) => sageCaSbsErpSage300IcWebApiModelsCategorySchemaResponseTransformer(item))
	}
	return data
}

export const icCategoriesGetByApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<IcCategoriesGetByApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsCategorySchemaResponseTransformer(data)
	return data
}

export const icCategoriesGetByCategorycodeAndApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<IcCategoriesGetByCategorycodeAndApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsCategorySchemaResponseTransformer(data)
	return data
}

const sageCaSbsErpSage300IcWebApiModelsItemPricingDetailSchemaResponseTransformer = (data: any) => {
	if (data.SaleStart) {
		data.SaleStart = new Date(data.SaleStart)
	}
	if (data.SaleEnd) {
		data.SaleEnd = new Date(data.SaleEnd)
	}
	if (data.LastPriceChangeDate) {
		data.LastPriceChangeDate = new Date(data.LastPriceChangeDate)
	}
	return data
}

const sageCaSbsErpSage300IcWebApiModelsItemPricingSchemaResponseTransformer = (data: any) => {
	if (data.LastMarkupCostChangeDate) {
		data.LastMarkupCostChangeDate = new Date(data.LastMarkupCostChangeDate)
	}
	if (data.LastExchangeRateChangeDate) {
		data.LastExchangeRateChangeDate = new Date(data.LastExchangeRateChangeDate)
	}
	if (data.SaleStartDate) {
		data.SaleStartDate = new Date(data.SaleStartDate)
	}
	if (data.SaleEndDate) {
		data.SaleEndDate = new Date(data.SaleEndDate)
	}
	if (data.BaseRateDate) {
		data.BaseRateDate = new Date(data.BaseRateDate)
	}
	if (data.SaleRateDate) {
		data.SaleRateDate = new Date(data.SaleRateDate)
	}
	if (data.PriceListStartDate) {
		data.PriceListStartDate = new Date(data.PriceListStartDate)
	}
	if (data.PriceListEndDate) {
		data.PriceListEndDate = new Date(data.PriceListEndDate)
	}
	if (data.ItemPricingDetails) {
		data.ItemPricingDetails = data.ItemPricingDetails.map((item: any) => sageCaSbsErpSage300IcWebApiModelsItemPricingDetailSchemaResponseTransformer(item))
	}
	return data
}

const swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsItemPricingSchemaResponseTransformer = (data: any) => {
	if (data.value) {
		data.value = data.value.map((item: any) => sageCaSbsErpSage300IcWebApiModelsItemPricingSchemaResponseTransformer(item))
	}
	return data
}

export const icItemPricingGetByApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<IcItemPricingGetByApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsItemPricingSchemaResponseTransformer(data)
	return data
}

export const icItemPricingGetByCurrencycodeAndUnformatteditemnumberAndPricelistcodeAndApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<IcItemPricingGetByCurrencycodeAndUnformatteditemnumberAndPricelistcodeAndApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsItemPricingSchemaResponseTransformer(data)
	return data
}

const sageCaSbsErpSage300IcWebApiModelsItemOptionalFieldSchemaResponseTransformer = (data: any) => {
	if (data.TypedValueFieldIndex) {
		data.TypedValueFieldIndex = BigInt(data.TypedValueFieldIndex.toString())
	}
	if (data.IntegerValue) {
		data.IntegerValue = BigInt(data.IntegerValue.toString())
	}
	if (data.DateValue) {
		data.DateValue = new Date(data.DateValue)
	}
	if (data.TimeValue) {
		data.TimeValue = new Date(data.TimeValue)
	}
	return data
}

const sageCaSbsErpSage300IcWebApiModelsItemSerialOptionalFieldSchemaResponseTransformer = (data: any) => {
	if (data.TypedValueFieldIndex) {
		data.TypedValueFieldIndex = BigInt(data.TypedValueFieldIndex.toString())
	}
	if (data.IntegerValue) {
		data.IntegerValue = BigInt(data.IntegerValue.toString())
	}
	if (data.DateValue) {
		data.DateValue = new Date(data.DateValue)
	}
	if (data.TimeValue) {
		data.TimeValue = new Date(data.TimeValue)
	}
	return data
}

const sageCaSbsErpSage300IcWebApiModelsItemLotOptionalFieldSchemaResponseTransformer = (data: any) => {
	if (data.TypedValueFieldIndex) {
		data.TypedValueFieldIndex = BigInt(data.TypedValueFieldIndex.toString())
	}
	if (data.IntegerValue) {
		data.IntegerValue = BigInt(data.IntegerValue.toString())
	}
	if (data.DateValue) {
		data.DateValue = new Date(data.DateValue)
	}
	if (data.TimeValue) {
		data.TimeValue = new Date(data.TimeValue)
	}
	return data
}

const sageCaSbsErpSage300IcWebApiModelsItemSchemaResponseTransformer = (data: any) => {
	if (data.AlternateItemSetNumber) {
		data.AlternateItemSetNumber = BigInt(data.AlternateItemSetNumber.toString())
	}
	if (data.DateLastMaintained) {
		data.DateLastMaintained = new Date(data.DateLastMaintained)
	}
	if (data.DateInactive) {
		data.DateInactive = new Date(data.DateInactive)
	}
	if (data.NumberOfOptionalFields) {
		data.NumberOfOptionalFields = BigInt(data.NumberOfOptionalFields.toString())
	}
	if (data.SerialsOptionalFields) {
		data.SerialsOptionalFields = BigInt(data.SerialsOptionalFields.toString())
	}
	if (data.LotsOptionalFields) {
		data.LotsOptionalFields = BigInt(data.LotsOptionalFields.toString())
	}
	if (data.ItemOptionalFields) {
		data.ItemOptionalFields = data.ItemOptionalFields.map((item: any) => sageCaSbsErpSage300IcWebApiModelsItemOptionalFieldSchemaResponseTransformer(item))
	}
	if (data.ItemSerialOptionalFields) {
		data.ItemSerialOptionalFields = data.ItemSerialOptionalFields.map((item: any) => sageCaSbsErpSage300IcWebApiModelsItemSerialOptionalFieldSchemaResponseTransformer(item))
	}
	if (data.ItemLotOptionalFields) {
		data.ItemLotOptionalFields = data.ItemLotOptionalFields.map((item: any) => sageCaSbsErpSage300IcWebApiModelsItemLotOptionalFieldSchemaResponseTransformer(item))
	}
	return data
}

const swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsItemSchemaResponseTransformer = (data: any) => {
	if (data.value) {
		data.value = data.value.map((item: any) => sageCaSbsErpSage300IcWebApiModelsItemSchemaResponseTransformer(item))
	}
	return data
}

export const icItemsGetByApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<IcItemsGetByApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsItemSchemaResponseTransformer(data)
	return data
}

export const icItemsGetByUnformatteditemnumberAndApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<IcItemsGetByUnformatteditemnumberAndApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300IcWebApiModelsItemSchemaResponseTransformer(data)
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceDetailOptionalFieldSchemaResponseTransformer = (data: any) => {
	if (data.TypedValueFieldIndex) {
		data.TypedValueFieldIndex = BigInt(data.TypedValueFieldIndex.toString())
	}
	if (data.IntegerValue) {
		data.IntegerValue = BigInt(data.IntegerValue.toString())
	}
	if (data.DateValue) {
		data.DateValue = new Date(data.DateValue)
	}
	if (data.TimeValue) {
		data.TimeValue = new Date(data.TimeValue)
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceBomDetailSchemaResponseTransformer = (data: any) => {
	if (data.ParentComponentNumber) {
		data.ParentComponentNumber = BigInt(data.ParentComponentNumber.toString())
	}
	if (data.ComponentNumber) {
		data.ComponentNumber = BigInt(data.ComponentNumber.toString())
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceKittingSerialNumberSchemaResponseTransformer = (data: any) => {
	if (data.ParentComponentNumber) {
		data.ParentComponentNumber = BigInt(data.ParentComponentNumber.toString())
	}
	if (data.ComponentNumber) {
		data.ComponentNumber = BigInt(data.ComponentNumber.toString())
	}
	if (data.TransactionQuantity) {
		data.TransactionQuantity = BigInt(data.TransactionQuantity.toString())
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceKittingDetailLotNumberSchemaResponseTransformer = (data: any) => {
	if (data.ParentComponentNumber) {
		data.ParentComponentNumber = BigInt(data.ParentComponentNumber.toString())
	}
	if (data.ComponentNumber) {
		data.ComponentNumber = BigInt(data.ComponentNumber.toString())
	}
	if (data.ExpirationDate) {
		data.ExpirationDate = new Date(data.ExpirationDate)
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceKittingDetailSchemaResponseTransformer = (data: any) => {
	if (data.ParentComponentNumber) {
		data.ParentComponentNumber = BigInt(data.ParentComponentNumber.toString())
	}
	if (data.ComponentNumber) {
		data.ComponentNumber = BigInt(data.ComponentNumber.toString())
	}
	if (data.SerialQuantity) {
		data.SerialQuantity = BigInt(data.SerialQuantity.toString())
	}
	if (data.SerialLotWindowHandle) {
		data.SerialLotWindowHandle = BigInt(data.SerialLotWindowHandle.toString())
	}
	if (data.InvoiceKittingSerialNumbers) {
		data.InvoiceKittingSerialNumbers = data.InvoiceKittingSerialNumbers.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceKittingSerialNumberSchemaResponseTransformer(item))
	}
	if (data.InvoiceKittingDetailLotNumber) {
		data.InvoiceKittingDetailLotNumber = data.InvoiceKittingDetailLotNumber.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceKittingDetailLotNumberSchemaResponseTransformer(item))
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceDetailSerialNumberSchemaResponseTransformer = (data: any) => {
	if (data.TransactionQuantity) {
		data.TransactionQuantity = BigInt(data.TransactionQuantity.toString())
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceDetailLotNumberSchemaResponseTransformer = (data: any) => {
	if (data.ExpirationDate) {
		data.ExpirationDate = new Date(data.ExpirationDate)
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceDetailSchemaResponseTransformer = (data: any) => {
	if (data.ShipmentDate) {
		data.ShipmentDate = new Date(data.ShipmentDate)
	}
	if (data.OrderDate) {
		data.OrderDate = new Date(data.OrderDate)
	}
	if (data.SHIDATE) {
		data.SHIDATE = new Date(data.SHIDATE)
	}
	if (data.NumberOfOptionalFields) {
		data.NumberOfOptionalFields = BigInt(data.NumberOfOptionalFields.toString())
	}
	if (data.RetainageDueDate) {
		data.RetainageDueDate = new Date(data.RetainageDueDate)
	}
	if (data.SerialQuantity) {
		data.SerialQuantity = BigInt(data.SerialQuantity.toString())
	}
	if (data.SerialLotWindowHandle) {
		data.SerialLotWindowHandle = BigInt(data.SerialLotWindowHandle.toString())
	}
	if (data.SageCRMCompanyID) {
		data.SageCRMCompanyID = BigInt(data.SageCRMCompanyID.toString())
	}
	if (data.SageCRMOpportunityID) {
		data.SageCRMOpportunityID = BigInt(data.SageCRMOpportunityID.toString())
	}
	if (data.InvoiceDetailOptionalFields) {
		data.InvoiceDetailOptionalFields = data.InvoiceDetailOptionalFields.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceDetailOptionalFieldSchemaResponseTransformer(item))
	}
	if (data.InvoiceBOMDetails) {
		data.InvoiceBOMDetails = data.InvoiceBOMDetails.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceBomDetailSchemaResponseTransformer(item))
	}
	if (data.InvoiceKittingDetails) {
		data.InvoiceKittingDetails = data.InvoiceKittingDetails.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceKittingDetailSchemaResponseTransformer(item))
	}
	if (data.InvoiceDetailSerialNumbers) {
		data.InvoiceDetailSerialNumbers = data.InvoiceDetailSerialNumbers.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceDetailSerialNumberSchemaResponseTransformer(item))
	}
	if (data.InvoiceDetailLotNumbers) {
		data.InvoiceDetailLotNumbers = data.InvoiceDetailLotNumbers.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceDetailLotNumberSchemaResponseTransformer(item))
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoicePaymentScheduleSchemaResponseTransformer = (data: any) => {
	if (data.DiscountDate) {
		data.DiscountDate = new Date(data.DiscountDate)
	}
	if (data.DueDate) {
		data.DueDate = new Date(data.DueDate)
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceOptionalFieldSchemaResponseTransformer = (data: any) => {
	if (data.TypedValueFieldIndex) {
		data.TypedValueFieldIndex = BigInt(data.TypedValueFieldIndex.toString())
	}
	if (data.IntegerValue) {
		data.IntegerValue = BigInt(data.IntegerValue.toString())
	}
	if (data.DateValue) {
		data.DateValue = new Date(data.DateValue)
	}
	if (data.TimeValue) {
		data.TimeValue = new Date(data.TimeValue)
	}
	return data
}

const sageCaSbsErpSage300OeWebApiModelsInvoiceSchemaResponseTransformer = (data: any) => {
	if (data.OrderDate) {
		data.OrderDate = new Date(data.OrderDate)
	}
	if (data.ShipmentDate) {
		data.ShipmentDate = new Date(data.ShipmentDate)
	}
	if (data.InvoiceDate) {
		data.InvoiceDate = new Date(data.InvoiceDate)
	}
	if (data.TermsPaymentsAsOfDate) {
		data.TermsPaymentsAsOfDate = new Date(data.TermsPaymentsAsOfDate)
	}
	if (data.PostingDate) {
		data.PostingDate = new Date(data.PostingDate)
	}
	if (data.CompletionDate) {
		data.CompletionDate = new Date(data.CompletionDate)
	}
	if (data.InvoiceRateDate) {
		data.InvoiceRateDate = new Date(data.InvoiceRateDate)
	}
	if (data.ShipmentRateDate) {
		data.ShipmentRateDate = new Date(data.ShipmentRateDate)
	}
	if (data.PrepaymentCheckDate) {
		data.PrepaymentCheckDate = new Date(data.PrepaymentCheckDate)
	}
	if (data.PrepaymentRateDate) {
		data.PrepaymentRateDate = new Date(data.PrepaymentRateDate)
	}
	if (data.NumberOfOptionalFields) {
		data.NumberOfOptionalFields = BigInt(data.NumberOfOptionalFields.toString())
	}
	if (data.LastInvoiceDate) {
		data.LastInvoiceDate = new Date(data.LastInvoiceDate)
	}
	if (data.LastPaymentDate) {
		data.LastPaymentDate = new Date(data.LastPaymentDate)
	}
	if (data.TRRateDate) {
		data.TRRateDate = new Date(data.TRRateDate)
	}
	if (data.TRShipmentRateDate) {
		data.TRShipmentRateDate = new Date(data.TRShipmentRateDate)
	}
	if (data.TaxVersion) {
		data.TaxVersion = BigInt(data.TaxVersion.toString())
	}
	if (data.JobRelatedDetailLines) {
		data.JobRelatedDetailLines = BigInt(data.JobRelatedDetailLines.toString())
	}
	if (data.DATEBUS) {
		data.DATEBUS = new Date(data.DATEBUS)
	}
	if (data.InvoiceDetails) {
		data.InvoiceDetails = data.InvoiceDetails.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceDetailSchemaResponseTransformer(item))
	}
	if (data.InvoicePaymentSchedules) {
		data.InvoicePaymentSchedules = data.InvoicePaymentSchedules.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoicePaymentScheduleSchemaResponseTransformer(item))
	}
	if (data.InvoiceOptionalFields) {
		data.InvoiceOptionalFields = data.InvoiceOptionalFields.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceOptionalFieldSchemaResponseTransformer(item))
	}
	return data
}

const swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300OeWebApiModelsInvoiceSchemaResponseTransformer = (data: any) => {
	if (data.value) {
		data.value = data.value.map((item: any) => sageCaSbsErpSage300OeWebApiModelsInvoiceSchemaResponseTransformer(item))
	}
	return data
}

export const oeInvoicesGetByApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<OeInvoicesGetByApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300OeWebApiModelsInvoiceSchemaResponseTransformer(data)
	return data
}

export const oeInvoicesGetByInvoiceuniquifierAndApiversionAndTenantAndCompanyResponseTransformer = async (data: any): Promise<OeInvoicesGetByInvoiceuniquifierAndApiversionAndTenantAndCompanyResponse> => {
	data = swashbuckleODataODataResponseSystemCollectionsGenericListSageCaSbsErpSage300OeWebApiModelsInvoiceSchemaResponseTransformer(data)
	return data
}
