/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export enum QueueJobState {
	ACTIVE = "active",
	CANCELLED = "cancelled",
	COMPLETED = "completed",
	CREATED = "created",
	FAILED = "failed",
	RETRY = "retry",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
	[x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface AuditLogs {
	action: string
	actor_user_id: number | null
	archived_at: Timestamp | null
	created_at: Generated<Timestamp>
	id: Generated<string>
	ip_address: string | null
	metadata: Generated<Json>
	summary: string
	target_id: string | null
	target_type: string
	user_agent: string | null
}

export interface BrandSettings {
	accent_color: string
	created_at: Generated<Timestamp>
	id: number
	logo_data_url: string | null
	org_name: string
	primary_color: string
	radius: Generated<string>
	sidebar_color: string
	surface_color: Generated<string>
	tagline: string
	theme: Json
	updated_at: Timestamp | null
}

export interface CartItems {
	created_at: Generated<Timestamp>
	id: Generated<number>
	quantity: number
	source_key: string
	updated_at: Timestamp | null
	user_id: number
}

export interface EmailAuthTokens {
	created_at: Generated<Timestamp>
	expires_at: Timestamp
	id: Generated<number>
	ip_address: string | null
	revoked_at: Timestamp | null
	token_hash: string
	used_at: Timestamp | null
	user_agent: string | null
	user_id: number
}

export interface Enquiries {
	created_at: Generated<Timestamp>
	enquiry_number: string
	id: Generated<number>
	priority: Generated<string>
	product_sku: string | null
	source_reference: string | null
	source_type: Generated<string>
	status: Generated<string>
	subject: string
	supplier_name: Generated<string>
	updated_at: Timestamp | null
	user_id: number
}

export interface EnquiryMessages {
	attachment_name: string | null
	author_name: string
	author_role: string
	author_user_id: number | null
	body: string
	created_at: Generated<Timestamp>
	enquiry_id: number
	id: Generated<number>
}

export interface QueueBam {
	command: string
	completed_on: Timestamp | null
	created_on: Generated<Timestamp>
	error: string | null
	id: Generated<string>
	name: string
	queue: string | null
	started_on: Timestamp | null
	status: Generated<string>
	table_name: string
	version: number
}

export interface QueueJob {
	blocked: Generated<boolean>
	blocking: Generated<boolean>
	completed_on: Timestamp | null
	created_on: Generated<Timestamp>
	data: Json | null
	dead_letter: string | null
	deletion_seconds: Generated<number>
	expire_seconds: Generated<number>
	group_id: string | null
	group_tier: string | null
	heartbeat_on: Timestamp | null
	heartbeat_seconds: number | null
	id: Generated<string>
	keep_until: Generated<Timestamp>
	name: string
	output: Json | null
	pending_dependencies: Generated<number>
	policy: string | null
	priority: Generated<number>
	retry_backoff: Generated<boolean>
	retry_count: Generated<number>
	retry_delay: Generated<number>
	retry_delay_max: number | null
	retry_limit: Generated<number>
	singleton_key: string | null
	singleton_on: Timestamp | null
	start_after: Generated<Timestamp>
	started_on: Timestamp | null
	state: Generated<QueueJobState>
}

export interface QueueJobDependency {
	child_id: string
	child_name: string
	parent_id: string
	parent_name: string
}

export interface QueueQueue {
	active_count: Generated<number>
	created_on: Generated<Timestamp>
	dead_letter: string | null
	deferred_count: Generated<number>
	deletion_seconds: number
	expire_seconds: number
	heartbeat_seconds: number | null
	maintain_on: Timestamp | null
	monitor_on: Timestamp | null
	name: string
	partition: boolean
	policy: string
	queued_count: Generated<number>
	retention_seconds: number
	retry_backoff: boolean
	retry_delay: number
	retry_delay_max: number | null
	retry_limit: number
	singletons_active: string[] | null
	table_name: string
	total_count: Generated<number>
	updated_on: Generated<Timestamp>
	warning_queued: Generated<number>
}

export interface QueueSchedule {
	created_on: Generated<Timestamp>
	cron: string
	data: Json | null
	key: Generated<string>
	name: string
	options: Json | null
	timezone: string | null
	updated_on: Generated<Timestamp>
}

export interface QueueSubscription {
	created_on: Generated<Timestamp>
	event: string
	name: string
	updated_on: Generated<Timestamp>
}

export interface QueueVersion {
	bam_on: Timestamp | null
	cron_on: Timestamp | null
	version: number
}

export interface QueueWarning {
	created_on: Generated<Timestamp>
	data: Json | null
	id: Generated<string>
	message: string
	type: string
}

export interface Users {
	created_at: Generated<Timestamp>
	deactivated: Generated<boolean>
	email: string
	email_verified: Generated<boolean>
	id: Generated<number>
	last_active_at: Timestamp | null
	name: string | null
	password_hash: string | null
	password_reset_required: Generated<boolean>
	password_set_at: Timestamp | null
	role: Generated<string>
	sage_customer_name: string | null
	sage_customer_number: string | null
	updated_at: Timestamp | null
}

export interface DB {
	"audit_logs": AuditLogs
	"brand_settings": BrandSettings
	"cart_items": CartItems
	"email_auth_tokens": EmailAuthTokens
	"enquiries": Enquiries
	"enquiry_messages": EnquiryMessages
	"queue.bam": QueueBam
	"queue.job": QueueJob
	"queue.job_dependency": QueueJobDependency
	"queue.queue": QueueQueue
	"queue.schedule": QueueSchedule
	"queue.subscription": QueueSubscription
	"queue.version": QueueVersion
	"queue.warning": QueueWarning
	"users": Users
}
